### ISSUE TITLE
What are the contents of list.txt and meta.txt?

### ISSUE THREAD

**Issue by wangyujie413** [XiaohangZhan/face_recognition_framework#1]
Thanks for your great work !
Could you provide an example or a screenshot about the contents of list.txt and meta.txt to help us better understand your code ?

    data_list:
        - 'data/emore/list.txt'
    data_meta:
        - 'data/emore/meta.txt'

**Comment by XiaohangZhan** [comment]
list: file name with relative path
meta: first line: "num_image [space] num_class", eg, "5783772 85738" for emore; other lines: category labels

**Comment by XiaohangZhan** [comment]
Hi, it is updated. Now it needs a list file with "path [space] label" in each line. No meta file anymore.
