### ISSUE TITLE
No module named 'test'

### ISSUE THREAD

**Issue by yuyq96** [XiaohangZhan/face_recognition_framework#2]
Seems like module 'test' is missing in current version, is it changed to evaluation? Also, benchmarks for IJB-A, LFW, CFP-FF, CFP-FP, AgeDB-30, calfw, cplfw are nowhere to be found.

**Comment by XiaohangZhan** [comment]
Hi, module 'test' is not needed. I removed it now. Benchmarks for those except for IJB-A and MegaFace are located in evaluation/verify.py. The testing data are included in the data folder, e.g., data/ms1m/lfw.bin, once you correctly preprocess the data following the README. The testing code for IJB-A is not ready for now.

**Comment by yuyq96** [comment]
Thanks! But there is still some code related to 'test' in datasets.py.

**Comment by XiaohangZhan** [comment]
Thank you for pointing it out. Updated now.

**Comment by yuyq96** [comment]
It works now, thank you.
