### ISSUE TITLE
about pretrained models

### ISSUE THREAD

**Issue by oukohou** [XiaohangZhan/face_recognition_framework#3]
Thanks for your great work!
Is it possible that you provide your pretrained models?

**Comment by XiaohangZhan** [comment]
Yes I can release the pre-trained model, but note that I currently have no time to adjust hyper-parameters. Hence it is NOT the state-of-the-art. E.g., the best model I trained is in experiments/ms1m/densenet121-arc-bs64-sz224-ep14 which achieves 0.9287 on MegaFace. Please download them from https://drive.google.com/open?id=1bJqhFBMkxqYsyIgWaEGOdoBkbmLBZ1zq

**Comment by oukohou** [comment]
Thanks for your immediate reply, I will try that~~
